//**************************************************************************************************
// DO NOT EDIT THIS FILE - Auto generated
//
// Used for frontend icon selection in Lcf.Select
// use 'run fe-icons' to generate this file from .svg files
//**************************************************************************************************

import Apple from './assets/Apple.svg';
import ArrowDown from './assets/ArrowDown.svg';
import ArrowLeft from './assets/ArrowLeft.svg';
import ArrowRight from './assets/ArrowRight.svg';
import ArrowUp from './assets/ArrowUp.svg';
import BrowseGallery from './assets/BrowseGallery.svg';
import Building from './assets/Building.svg';
import Business from './assets/Business.svg';
import BusinessTag from './assets/BusinessTag.svg';
import Calendar from './assets/Calendar.svg';
import Car from './assets/Car.svg';
import Checkmark from './assets/Checkmark.svg';
import CheckmarkWhite from './assets/CheckmarkWhite.svg';
import ChevronDown from './assets/ChevronDown.svg';
import ChevronLeft from './assets/ChevronLeft.svg';
import ChevronRight from './assets/ChevronRight.svg';
import ChevronUp from './assets/ChevronUp.svg';
import Clocks from './assets/Clocks.svg';
import Cognition from './assets/Cognition.svg';
import Cogs from './assets/Cogs.svg';
import Command from './assets/Command.svg';
import Cookie from './assets/Cookie.svg';
import Copy from './assets/Copy.svg';
import Cross from './assets/Cross.svg';
import Desktop from './assets/Desktop.svg';
import DirectionsCar from './assets/DirectionsCar.svg';
import Docs from './assets/Docs.svg';
import Document from './assets/Document.svg';
import Download from './assets/Download.svg';
import ElectricalServices from './assets/ElectricalServices.svg';
import Email from './assets/Email.svg';
import Energy from './assets/Energy.svg';
import Euro from './assets/Euro.svg';
import EvStation from './assets/EvStation.svg';
import Facebook from './assets/Facebook.svg';
import File from './assets/File.svg';
import FileUpload from './assets/FileUpload.svg';
import Fire from './assets/Fire.svg';
import Fullscreen from './assets/Fullscreen.svg';
import FullscreenExit from './assets/FullscreenExit.svg';
import Glob from './assets/Glob.svg';
import GooglePlay from './assets/GooglePlay.svg';
import HomeWork from './assets/HomeWork.svg';
import House from './assets/House.svg';
import Hub from './assets/Hub.svg';
import Info from './assets/Info.svg';
import Instagram from './assets/Instagram.svg';
import Linkedin from './assets/Linkedin.svg';
import LocalFireDepartment from './assets/LocalFireDepartment.svg';
import Menu from './assets/Menu.svg';
import Minus from './assets/Minus.svg';
import Mobile from './assets/Mobile.svg';
import MonitorHeart from './assets/MonitorHeart.svg';
import Moon from './assets/Moon.svg';
import PartlyCloudyDay from './assets/PartlyCloudyDay.svg';
import Pending from './assets/Pending.svg';
import Phone from './assets/Phone.svg';
import PiggyBank from './assets/PiggyBank.svg';
import Plus from './assets/Plus.svg';
import QuestionMark from './assets/QuestionMark.svg';
import Search from './assets/search.svg';
import Specto from './assets/Specto.svg';
import StarShine from './assets/StarShine.svg';
import StepInto from './assets/StepInto.svg';
import StepOut from './assets/StepOut.svg';
import Sun from './assets/Sun.svg';
import Sunrise from './assets/Sunrise.svg';
import Sunset from './assets/Sunset.svg';
import Tail from './assets/Tail.svg';
import Today from './assets/Today.svg';
import Trash from './assets/Trash.svg';
import Verified from './assets/Verified.svg';
import X from './assets/X.svg';
import Youtube from './assets/Youtube.svg';

export const icons: Record<string, string> = {
	Apple,
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	BrowseGallery,
	Building,
	Business,
	BusinessTag,
	Calendar,
	Car,
	Checkmark,
	CheckmarkWhite,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Clocks,
	Cognition,
	Cogs,
	Command,
	Cookie,
	Copy,
	Cross,
	Desktop,
	DirectionsCar,
	Docs,
	Document,
	Download,
	ElectricalServices,
	Email,
	Energy,
	Euro,
	EvStation,
	Facebook,
	File,
	FileUpload,
	Fire,
	Fullscreen,
	FullscreenExit,
	Glob,
	GooglePlay,
	HomeWork,
	House,
	Hub,
	Info,
	Instagram,
	Linkedin,
	LocalFireDepartment,
	Menu,
	Minus,
	Mobile,
	MonitorHeart,
	Moon,
	PartlyCloudyDay,
	Pending,
	Phone,
	PiggyBank,
	Plus,
	QuestionMark,
	Search,
	Specto,
	StarShine,
	StepInto,
	StepOut,
	Sun,
	Sunrise,
	Sunset,
	Tail,
	Today,
	Trash,
	Verified,
	X,
	Youtube,
};
