// Local stand-in for the website repo's `pnpm generate-icons` (cli/commands/fe-icons.sh).
// Writes the same IconVariants.ts from the SVGs in src/components/atoms/Icon/assets.
import { readdirSync, writeFileSync } from 'node:fs';

const dir = 'src/components/atoms/Icon';
const entries = readdirSync(`${dir}/assets`)
	.filter((file) => file.endsWith('.svg'))
	.map((file) => file.slice(0, -4))
	.map((name) => [name.replace(/(^|-|_)([a-z])/g, (_, __, letter) => letter.toUpperCase()).replace(/[-_]/g, ''), name])
	.sort(([a, x], [b, y]) => (a === b ? (x < y ? -1 : 1) : a < b ? -1 : 1));

const header = `//**************************************************************************************************
// DO NOT EDIT THIS FILE - Auto generated
//
// Used for frontend icon selection in Lcf.Select
// use 'run fe-icons' to generate this file from .svg files
//**************************************************************************************************
`;

writeFileSync(
	`${dir}/IconVariants.ts`,
	`${header}\n${entries.map(([variable, name]) => `import ${variable} from './assets/${name}.svg';`).join('\n')}\n\nexport const icons: Record<string, string> = {\n${entries.map(([variable]) => `\t${variable},`).join('\n')}\n};\n`,
);
console.log(`Generated ${entries.length} icons`);
